module.exports = ->
  console.log "Usage:"
  console.log "======"
  console.log "\t$ mamp list\n\t  List all available shortcuts\n"
  console.log "\t$ mamp add <shortcut>\n\t  Add the current working directory as shortcut\n"
  console.log "\t$ mamp remove <shortcut>\n\t  Remove the <shortcut> from your shortcuts\n"
  console.log "\t$ mamp switch <shortcut>\n\t  Switch the webroot of the server to <shortcut>\n"
  console.log "\t$ mamp start\n\t  Start mamp\n"
  console.log "\t$ mamp stop\n\t  Stop mamp\n"
  console.log "\t$ mamp restart\n\t  Restart Apache\n"
